name: Shared Setup Workflow

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version to set up"
        required: true
        type: string
      env-vars:
        description: "Environment variables as a multi-line string"
        required: false
        type: string

jobs:
  shared-setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Create .env file
        if: ${{ inputs.env-vars != '' }}
        run: |
          echo "${{ inputs.env-vars }}" > .env
